title: Products

files: false

pages:
  template: product

options: 
  template: false  
  status: false  
  url: false  

fields:
  title:
    label: Title
    type:  text

  text:
    label: Text
    type:  textarea
